-- AlterTable
ALTER TABLE "Anggota" ALTER COLUMN "tglLahir" SET DATA TYPE TEXT,
ALTER COLUMN "tempatLahir" DROP NOT NULL,
ALTER COLUMN "pendidikan" DROP NOT NULL,
ALTER COLUMN "pekerjaan" DROP NOT NULL,
ALTER COLUMN "agama" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "pendapatan" DROP NOT NULL,
ALTER COLUMN "noRek" DROP NOT NULL,
ALTER COLUMN "bank" DROP NOT NULL,
ALTER COLUMN "cabang" DROP NOT NULL,
ALTER COLUMN "noKtp" DROP NOT NULL,
ALTER COLUMN "noKk" DROP NOT NULL,
ALTER COLUMN "noNpwp" DROP NOT NULL,
ALTER COLUMN "noTelp" DROP NOT NULL,
ALTER COLUMN "noHp" DROP NOT NULL,
ALTER COLUMN "noReferensi" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL;

-- AlterTable
ALTER TABLE "BukuBesar" ADD COLUMN     "anggotaId" VARCHAR(50);

-- AlterTable
ALTER TABLE "Pinjaman" ADD COLUMN     "anggotaId" VARCHAR(50);

-- AlterTable
ALTER TABLE "Rekap" ADD COLUMN     "anggotaId" VARCHAR(50);

-- AlterTable
ALTER TABLE "Simpanan" ADD COLUMN     "anggotaId" VARCHAR(50);

-- AddForeignKey
ALTER TABLE "Pinjaman" ADD CONSTRAINT "Pinjaman_anggotaId_fkey" FOREIGN KEY ("anggotaId") REFERENCES "Anggota"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Simpanan" ADD CONSTRAINT "Simpanan_anggotaId_fkey" FOREIGN KEY ("anggotaId") REFERENCES "Anggota"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BukuBesar" ADD CONSTRAINT "BukuBesar_anggotaId_fkey" FOREIGN KEY ("anggotaId") REFERENCES "Anggota"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Rekap" ADD CONSTRAINT "Rekap_anggotaId_fkey" FOREIGN KEY ("anggotaId") REFERENCES "Anggota"("id") ON DELETE SET NULL ON UPDATE CASCADE;
